DE-3360: Fix the bug
tetrascience/ts-ids-core pull request #30
Opened 2022-02-26 00:22 UTC by VladimirShteyn

The correct IDS JSON Schema is now generated for `List[Union[None, T]]` types.

Note the change in the snapshots. The bug was sitting there in plain sight but we all missed it. To be fair, it's very easy to miss small but important details in snapshots.

2022-03-01 00:39 UTC, robjhornby-ts requested changes
Nice way of doing it, another good feature which vanilla Pydantic doesn't have. Just requesting changes for an unfinished sentence, the rest is ready to be approved

2022-03-01 00:39 UTC, robjhornby-ts commented on tests/base/test_ids_element.py
> +            warble: List[List[Nullable[str]]]
I wondered what would happen if `Nullable` came somewhere other than around the deepest nested annotation, so I tried both of these instead of this line, and all the tests pass for both:

`warble: Nullable[List[List[str]]]`

`warble: Nullable[List[Nullable[List[Nullable[str]]]]]`

I think this is a nice simple way of it working - Nullable means the underlying type of the collection can be nullable, no matter where it comes in the type annotation, and you can be redundant if you want to. Do you agree; should we document this somewhere; should we assert this behaviour with a test so it remains in future versions?

2022-03-01 19:38 UTC, VladimirShteyn commented on tests/base/test_ids_element.py
> +            warble: List[List[Nullable[str]]]
Good point. As discussed in a Slack Huddle, let's not allow the above types. Validating against them will be implemented in [this ticket](https://tetrascience.atlassian.net/browse/DE-3398).

I also made the implementation more logical and cleaner.

2022-03-01 19:38 UTC, VladimirShteyn commented on ts_ids_core/base/ids_element.py
> +                        raise ValueError
OBE because this function was deleted. See [this comment](https://github.com/tetrascience/ts-ids-core/pull/30#discussion_r817082729).

2022-03-01 19:38 UTC, VladimirShteyn commented on ts_ids_core/base/ids_element.py
> +                If the value is
Fixed.

2022-03-02 14:56 UTC, VladimirShteyn commented on ts_ids_core/base/ids_element.py
> +                    # If the field's type is `None` and the field is Not Required
This cleans up the logic of fields whose type hint is `None`. For example, 

```python
class MyClass(IdsElement):
  field: None
```

During the metaclass' `__new__` method, the type hint of `field` is converted to `Union[None, IdsUndefinedType]`. Its schema will be `{"type": "Undefined"}`. That's because 1. pydantic removes "null" from the schema and 2. the only non-null type is "IdsUndefinedType", which is represented in the JSON Schema as "Undefined" (see the `__modify_schema__` [method](https://github.com/tetrascience/ts-ids-core/blob/development/ts_ids_core/base/meta.py#L96)). 

If the field is 

```python
class MyOtherClass(IdsElement):
  other_field: Nullable[str]
```

During the metaclass' `__new__` method, its type hint will turn into `Union[None, str, IdsUndefinedType]`. The schema will look like `{"type": "string"}` after stripping out the `"Undefined"` by `_set_fields` ([link](https://github.com/tetrascience/ts-ids-core/blob/DE-3360-list-of-lists-null-value-bug/ts_ids_core/base/ids_element.py#L111-L144)). The `else` statement converts `{"type": "string"}` to `{"type": ["string", "null"]}`. Checking for `{"type": "Undefined"}` first means preventing invalid types like `{"type": ["Undefined", "null"]}`. Does this help?

2022-03-02 15:05 UTC, VladimirShteyn commented on ts_ids_core/base/ids_element.py
> +                    # If the field's type is `None` and the field is Not Required
> Is it true that this means the field is Not Required?

Yes.

2022-03-02 15:06 UTC, merged